name: Check and test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "npm"
      - run: npm ci
      - run: npx prettier -c "**/*.(js|jsx|mjs|ts|tsx)"
      - run: npx tsc -p client-vms/tsconfig.json
      - run: npx eslint -c eslint.config.mjs

  test-client-vms:
    if: false
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "npm"
      - uses: NillionNetwork/nillion-setup-action@main
        with:
          version: "latest"
      - run: |
          nillion-devnet --seed test-fixture &
          sleep 10
          just test-client-vms
          killall -9 nillion-devnet
