name: Check, build and test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: just check

  test:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ client-core, client-payments, client-vms ]
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: browser-actions/setup-chrome@v1
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler curl
          npm ci
      - name: Install and configure nilup
        run: |
          curl https://nilup.nilogy.xyz/install.sh | bash
          $HOME/.nilup/bin/nilup use 0.5.0
          $HOME/.nilup/bin/nilup init
          echo "$HOME/.nilup/bin" >> $GITHUB_PATH
      - run: |
          just test-${{ matrix.package }}-ci
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: ${{ matrix.package }}-logs
          path: packages/fixture/logs
          retention-days: 4
