name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "23"
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm exec biome format
      - run: pnpm exec biome lint
      - run: pnpm exec tsc -p client-vms/tsconfig.json

  test-client-vms:
    if: false
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "npm"
      - uses: NillionNetwork/nillion-setup-action@main
        with:
          version: "latest"
      - run: |
          nillion-devnet --seed test-fixture &
          sleep 10
          just test-client-vms
          killall -9 nillion-devnet
