name: Publish to npmjs

on:
  workflow_dispatch:

concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  publish:
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ client-wasm, client-core, client-payments, client-vms, client-react-hooks ]
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: "https://registry.npmjs.org"
          cache: 'npm'
      - env:
          NODE_AUTH_TOKEN:
            ${{ secrets.NPM_TOKEN }}
        run: |
          npm ci
          just publish-${{ matrix.package }} "--tag latest"
